name: Generate dependabot.yml

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Generate dependabot.yml
        uses: ./

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
